@extends('user.app')

@section('content')

<div class="min-h-screen bg-gradient-to-b from-[#FFE4E8] via-[#FFF6F7] to-white text-[#3A372E] pt-[94px] pb-[70px]">

    <!-- SUCCESS HEADER -->
    <section class="px-[36px] md:px-[42px] pt-[18px] text-center">
        <div class="mx-auto w-[96px] h-[96px] rounded-full bg-[#E8D8D1] flex items-center justify-center mb-[6px]">
            <div class="w-[64px] h-[64px] rounded-full bg-[#91B56C] flex items-center justify-center">
                <span class="text-white text-[44px] font-extrabold leading-none">
                    ✓
                </span>
            </div>
        </div>

        <h1 class="font-serif text-[54px] md:text-[68px] font-extrabold tracking-[-0.04em] leading-none">
            Booking Confirmed!
        </h1>
    </section>

    <!-- CONFIRMATION CARD -->
    <section class="px-[36px] md:px-[42px] mt-[46px]">
        <div class="max-w-[920px] mx-auto bg-white rounded-[24px] px-[70px] pt-[34px] pb-[54px]">

            <div class="grid grid-cols-1 md:grid-cols-[1.1fr_1fr] gap-[80px]">

                <!-- LEFT SIDE -->
                <div>
                    <p id="bookingIdText" class="text-[20px] font-medium text-[#854152] mb-[26px]">
                        Booking ID: #DM-260412
                    </p>

                    <!-- CLIENT DETAILS -->
                    <div>
                        <p class="text-[16px] font-medium text-[#854152] mb-[12px]">
                            Client details
                        </p>

                        <h2 id="clientNameText" class="text-[22px] font-extrabold leading-tight text-[#3A372E]">
                            Amelia Lee
                        </h2>

                        <p id="clientPhoneText" class="text-[21px] font-extrabold leading-tight text-[#3A372E]">
                            +62 812 3456 7890
                        </p>
                    </div>

                    <!-- EXPERIENCES -->
                    <div class="mt-[30px]">
                        <p class="text-[16px] font-medium text-[#854152] mb-[14px]">
                            Your experiences
                        </p>

                        <div id="experienceList" class="space-y-[8px]">
                            <!-- Generated by JS -->
                        </div>
                    </div>
                </div>

                <!-- RIGHT SIDE -->
                <div class="relative">
                    <div class="absolute right-0 top-[-16px]">
                        <p class="text-[16px] font-extrabold text-black leading-none">
                            Total Paid
                        </p>

                        <p id="totalPaidText" class="text-[31px] font-extrabold text-[#854152] leading-none mt-[5px]">
                            255k
                        </p>
                    </div>

                    <div class="pt-[52px]">

                        <!-- DATE & TIME -->
                        <div>
                            <p class="text-[16px] font-medium text-[#854152] mb-[12px]">
                                Date & time
                            </p>

                            <h2 id="dateText" class="text-[22px] font-extrabold leading-tight text-black">
                                Sunday, 12 April 2026
                            </h2>

                            <p id="timeText" class="text-[21px] font-extrabold leading-tight text-black">
                                At 10:30 AM
                            </p>
                        </div>

                        <!-- LOCATION -->
                        <div class="mt-[28px]">
                            <p class="text-[16px] font-medium text-[#854152] mb-[12px]">
                                Location
                            </p>

                            <h2 id="locationNameText" class="text-[22px] font-extrabold leading-tight text-black">
                                Cabang Tuasan
                            </h2>

                            <p id="locationAddressText" class="text-[18px] font-extrabold leading-tight text-black">
                                Jl. Tuasan No. 76
                            </p>
                        </div>

                        <!-- PAYMENT METHOD -->
                        <div class="mt-[28px]">
                            <p class="text-[16px] font-medium text-[#854152] mb-[12px]">
                                Payment method
                            </p>

                            <h2 id="paymentMethodText" class="text-[22px] font-extrabold leading-tight text-black">
                                Cash
                            </h2>

                            <p id="paymentDescriptionText" class="text-[16px] font-medium leading-tight text-black">
                                Pay at Salon
                            </p>
                        </div>

                    </div>
                </div>

            </div>

        </div>
    </section>

    <!-- ACTION BUTTONS -->
    <section class="px-[36px] md:px-[42px] mt-[40px]">
        <div class="max-w-[920px] mx-auto flex flex-col items-center gap-[22px]">

            <div class="flex flex-wrap justify-center gap-[35px]">
                <a href="{{ url('/pelanggan/bookings') }}"
                   class="w-[225px] bg-[#F8A9B4] text-[#3A372E] rounded-full py-[16px] text-center text-[19px] font-extrabold hover:bg-[#F47CA5] transition">
                    View Booking
                </a>

                <a href="{{ url('/contactsalon') }}"
                   class="w-[225px] bg-transparent border border-[#F8A9B4] text-[#6F5D5D] rounded-full py-[16px] text-center text-[19px] font-extrabold hover:bg-[#FFF0F3] transition">
                    Contact Salon
                </a>
            </div>

            <a href="{{ url('/') }}"
               class="w-[225px] bg-[#E4C2C5] text-[#6F5D5D] rounded-full py-[15px] text-center text-[18px] font-extrabold hover:bg-[#d8b1b5] transition">
                <span class="mr-2">←</span>
                Back to Home
            </a>

        </div>
    </section>

</div>

<script>
    function safeJsonParse(key) {
        try {
            return JSON.parse(localStorage.getItem(key) || 'null');
        } catch (error) {
            return null;
        }
    }

    function padNumber(number) {
        return String(number).padStart(2, '0');
    }

    function generateBookingId(dateText) {
        const now = new Date();
        const year = String(now.getFullYear()).slice(-2);
        const month = padNumber(now.getMonth() + 1);
        const day = padNumber(now.getDate());

        return '#DM-' + year + month + day;
    }

    function getFullDayName(shortDay) {
        const days = {
            Sun: 'Sunday',
            Mon: 'Monday',
            Tue: 'Tuesday',
            Wed: 'Wednesday',
            Thu: 'Thursday',
            Fri: 'Friday',
            Sat: 'Saturday'
        };

        return days[shortDay] || shortDay;
    }

    function formatFullDate(dateText) {
        if (!dateText) {
            return '-';
        }

        const currentYear = new Date().getFullYear();

        if (!dateText.includes(',')) {
            return dateText + ' ' + currentYear;
        }

        const parts = dateText.split(',');
        const dayName = getFullDayName(parts[0].trim());
        const datePart = parts[1].trim();

        return dayName + ', ' + datePart + ' ' + currentYear;
    }

    function loadConfirmationData() {
        const completeBooking = safeJsonParse('complete_booking');
        const bookingCart = completeBooking?.cart || safeJsonParse('booking_cart');
        const bookingLocation = completeBooking?.location || safeJsonParse('booking_location');
        const bookingTime = completeBooking?.time || safeJsonParse('booking_time');
        const bookingDetails = completeBooking?.customer || safeJsonParse('booking_details');
        const bookingPayment = completeBooking?.payment || safeJsonParse('booking_payment');

        const bookingId = completeBooking?.bookingId
            || localStorage.getItem('booking_id')
            || generateBookingId(bookingTime?.date);

        localStorage.setItem('booking_id', bookingId);

        const services = bookingCart?.services || [];
        const total = bookingCart?.total || '0k';

        const clientName = bookingDetails?.fullName || 'Amelia Lee';
        const clientPhone = bookingDetails?.phoneNumber || '+62 812 3456 7890';

        const dateText = formatFullDate(bookingTime?.date || 'Sun, 12 April');
        const timeText = bookingTime?.time || '10:30 AM';

        const locationName = bookingLocation?.name || 'Tuasan';
        const locationAddress = bookingLocation?.address || 'Jl. Tuasan No. 76';

        const specialistName = bookingTime?.specialistName || 'Natalie';

        const paymentLabel = bookingPayment?.label || 'Cash';
        const paymentDescription = paymentLabel === 'E-Wallet'
            ? 'GoPay, OVO, or Dana'
            : 'Pay at Salon';

        document.getElementById('bookingIdText').textContent = 'Booking ID: ' + bookingId;
        document.getElementById('clientNameText').textContent = clientName;
        document.getElementById('clientPhoneText').textContent = clientPhone;
        document.getElementById('totalPaidText').textContent = total;
        document.getElementById('dateText').textContent = dateText;
        document.getElementById('timeText').textContent = 'At ' + timeText;
        document.getElementById('locationNameText').textContent = 'Cabang ' + locationName;
        document.getElementById('locationAddressText').textContent = locationAddress;
        document.getElementById('paymentMethodText').textContent = paymentLabel;
        document.getElementById('paymentDescriptionText').textContent = paymentDescription;

        const experienceList = document.getElementById('experienceList');
        experienceList.innerHTML = '';

        if (services.length > 0) {
            services.forEach((service) => {
                const item = document.createElement('div');

                item.innerHTML = `
                    <h3 class="text-[22px] font-extrabold leading-tight text-[#3A372E]">
                        ${service.name}
                    </h3>

                    <p class="text-[16px] font-medium text-[#854152] leading-tight">
                        with <span class="font-extrabold">${specialistName}</span>
                    </p>
                `;

                experienceList.appendChild(item);
            });
        } else {
            experienceList.innerHTML = `
                <div>
                    <h3 class="text-[22px] font-extrabold leading-tight text-[#3A372E]">
                        No service selected
                    </h3>

                    <p class="text-[16px] font-medium text-[#854152] leading-tight">
                        Please choose your treatment first
                    </p>
                </div>
            `;
        }

        const updatedCompleteBooking = {
            bookingId: bookingId,
            cart: bookingCart,
            location: bookingLocation,
            time: bookingTime,
            customer: bookingDetails,
            payment: bookingPayment,
            status: 'confirmed',
            confirmedAt: new Date().toISOString()
        };

        localStorage.setItem('complete_booking', JSON.stringify(updatedCompleteBooking));
    }

    loadConfirmationData();
</script>

@endsection